### ISSUE TITLE
Automatically show keyboard when tapping "+"

### ISSUE THREAD

**Issue by wtimme** [spacepandas/cineaste-ios#103]
**Is your feature request related to a problem? Please describe.**
For me, the most common usecase of "Add movie" is when I get a recommendation from a friend, and they usually tell me the title (or parts of it). When I then want to search for it, I need to tap two times before I can actually enter text.

**Describe the solution you'd like**
When I tap the "+" button in the top right corner and the "Add movie" screen becomes visible, the search bar should automatically be focused, with the keyboard visible, so that I can start typing.

**Describe alternatives you've considered**
People might want to use the "popular" movies and are not interested in searching, so they might be annoyed by the proposed behaviour. We could configure the keyboard so that it is dismissed when the user scrolls, removing the need to tap "Cancel".

**Comment by fbernutz** [comment]
I like this idea! If you want to you can add a PR for this. I'm also bored to tap cancel to dismiss the keyboard and then have to tap Done to dismiss the search.

**Comment by fbernutz** [comment]
The UI changed a bit since July last year and it will change a bit more for the search tab in the near future. This is not longer as relevant as it was before. So, I'm closing this. Thanks for the feedback anyway.
