### ISSUE TITLE
Slide hint not visible when opening "Add movie" for the very first time

### ISSUE THREAD

**Issue by wtimme** [spacepandas/cineaste-ios#107]
**Describe the bug**
The very first time the user opens "Add movie", the hint for the table view cell's slide action is not visible. Only after closing and opening the screen for a second time, the hint is visible.

**To Reproduce**

1. Remove the app from the device (to reset `UserDefaults`)
2. Install and start the app
3. On the first screen, tap "Add movie"
4. Wait until the "trending" movies are displayed

Closely watch the first cell.

**Expected behavior**
The "slide action" hint is visible.

**Observed behaviour:**
The "slide action" hint is _not_ visible.

**Smartphone (please complete the following information):**
 - Device: iPhone X Simulator
 - iOS: 11.0.1
 - App-Version: 1.10.0 (452)

**Additional context**
I encountered the bug while testing #104.

**Comment by fbernutz** [comment]
I can't reproduce it anymore with the current version 1.20.1
