### ISSUE TITLE
Slide hint is animating in the second instead of the first cell when searching

### ISSUE THREAD

**Issue by wtimme** [spacepandas/cineaste-ios#109]
**Describe the bug**
When searching for a movie and reviewing the details for search results, the "slide" hint is animated in the second cell, not the first one.

**To Reproduce**

1. Start the app
2. Tap on the "+" button
3. Tap on the search bar and enter at least one character, e. g. "f"
4. Wait for the search results to load, and make sure it's more than two
5. Tap on the first result
6. Use the navigation bar to get back to the list

Closely watch the first two cells.

**Expected behavior**
The "slide action" hint is visible on the _first_ cell.

**Observed behaviour:**
The "slide action" hint is visible on the *second* cell.

**Screenshots**
![slide-hint-on-second-cell](https://user-images.githubusercontent.com/1681085/61250179-945a3580-a746-11e9-88f8-b30ca79f6350.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone X Simulator
- iOS: 11.0.1
- App-Version: 1.10.0 (452)

**Comment by fbernutz** [comment]
This is definitely a bug, but I'm not sure if it really matters which cell is animated, because the hint is only shown three times right now.
