### ISSUE TITLE
Only show "slide" hint on "Add Movie" screen only once

### ISSUE THREAD

**Issue by wtimme** [spacepandas/cineaste-ios#98]
**Is your feature request related to a problem? Please describe.**
Whenever I enter the "Add Movie" screen, the first table view cell is animated as some kind of "hint" to remind me that the cell has available actions. This helped me the first time I interacted with the app and I like it, however, now that I know this gesture exists, I would like this animation to no longer appear.

**Describe the solution you'd like**
The app should understand that the user is capable of learning, and should only show this hint a couple of times (e. g. only once or twice).

**Describe alternatives you've considered**
The app could also show this hint until the gesture/actions were used. I feel like this "forces" the user to make use of these actions, and would therefore recommend against this approach.

**Comment by fbernutz** [comment]
Done with #104
